package com.example.pearl.presentation.skin_quiz

enum class QuizStage {
    GENDER_SELECTION,
    GENERAL_QUESTIONS,
    NUTRITION_START,
    NUTRITION_QUESTIONS,
    QUIZ_ENDING,
    FIRST_QUIZ_ENDING_SCREEN,
    SECOND_QUIZ_ENDING_SCREEN,
    THIRD_QUIZ_ENDING_SCREEN,
    LAST_QUIZ_ENDING_SCREEN
}